services:
  - type: web
    name: blogging-system
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://yadavhimanshu88272_db_user:Majar%40123@cluster0.mfempxz.mongodb.net/bloggingDB?retryWrites=true&w=majority
      - key: PORT
        value: 10000
